### ISSUE TITLE
Cannot copy URL after opening 'Customise Toolbar'

### ISSUE THREAD

**Issue by p1usminus** [117649/AdvancedLocationbar#3] opened 2021-04-07 17:54 UTC
FF Dev 88

![image](https://user-images.githubusercontent.com/50540305/113911706-2daa6480-97d2-11eb-998e-9f3dadc216fd.png)

![image](https://user-images.githubusercontent.com/50540305/113911759-40bd3480-97d2-11eb-95f6-e2844d99a2ca.png)

Using these options:
![image](https://user-images.githubusercontent.com/50540305/113911920-73672d00-97d2-11eb-859c-72290a09696b.png)

I can copy the URL again after restarting the browser.

**Comment by 117649** [comment] 2021-04-07 20:14
Can't reproduce this.
what version are you using?

**Comment by p1usminus** [comment] 2021-04-07 20:20
1.2.1.3

**Comment by 117649** [comment] 2021-04-08 06:09
See if [this](https://github.com/117649/AdvancedLocationbar2/commit/914ee555deafe676e36d30cb339cb762d343dcba) fix it for you.

**Comment by p1usminus** [comment] 2021-04-08 12:26
> 
> 
> See if [this](https://github.com/117649/AdvancedLocationbar2/commit/914ee555deafe676e36d30cb339cb762d343dcba) fix it for you.

Yes, no errors now, thank you 😀

**Comment by 117649** [comment] 2021-04-08 12:39
Fixed with https://github.com/117649/AdvancedLocationbar2/releases/tag/1.2.1.4

**Closed as completed by 117649** 2021-04-08 12:39 UTC
